from typing import Annotated

import numpy
from numpy.typing import NDArray

import roboplan_ext.core


class Node:
    def __init__(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], arg1: int, /) -> None: ...

    @property
    def config(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def parent_id(self) -> int: ...

class RRTOptions:
    def __init__(self) -> None: ...

    @property
    def group_name(self) -> str: ...

    @group_name.setter
    def group_name(self, arg: str, /) -> None: ...

    @property
    def max_nodes(self) -> int: ...

    @max_nodes.setter
    def max_nodes(self, arg: int, /) -> None: ...

    @property
    def max_connection_distance(self) -> float: ...

    @max_connection_distance.setter
    def max_connection_distance(self, arg: float, /) -> None: ...

    @property
    def collision_check_step_size(self) -> float: ...

    @collision_check_step_size.setter
    def collision_check_step_size(self, arg: float, /) -> None: ...

    @property
    def goal_biasing_probability(self) -> float: ...

    @goal_biasing_probability.setter
    def goal_biasing_probability(self, arg: float, /) -> None: ...

    @property
    def max_planning_time(self) -> float: ...

    @max_planning_time.setter
    def max_planning_time(self, arg: float, /) -> None: ...

    @property
    def rrt_connect(self) -> bool: ...

    @rrt_connect.setter
    def rrt_connect(self, arg: bool, /) -> None: ...

class RRT:
    def __init__(self, arg0: roboplan_ext.core.Scene, arg1: RRTOptions, /) -> None: ...

    def plan(self, arg0: roboplan_ext.core.JointConfiguration, arg1: roboplan_ext.core.JointConfiguration, /) -> roboplan_ext.core.JointPath: ...

    def setRngSeed(self, arg: int, /) -> None: ...

    def getNodes(self) -> tuple[list[Node], list[Node]]: ...
