import roboplan_ext.core


class SimpleIkOptions:
    def __init__(self) -> None: ...

    @property
    def group_name(self) -> str: ...

    @group_name.setter
    def group_name(self, arg: str, /) -> None: ...

    @property
    def max_iters(self) -> int: ...

    @max_iters.setter
    def max_iters(self, arg: int, /) -> None: ...

    @property
    def max_time(self) -> float: ...

    @max_time.setter
    def max_time(self, arg: float, /) -> None: ...

    @property
    def max_restarts(self) -> int: ...

    @max_restarts.setter
    def max_restarts(self, arg: int, /) -> None: ...

    @property
    def step_size(self) -> float: ...

    @step_size.setter
    def step_size(self, arg: float, /) -> None: ...

    @property
    def damping(self) -> float: ...

    @damping.setter
    def damping(self, arg: float, /) -> None: ...

    @property
    def max_error_norm(self) -> float: ...

    @max_error_norm.setter
    def max_error_norm(self, arg: float, /) -> None: ...

    @property
    def check_collisions(self) -> bool: ...

    @check_collisions.setter
    def check_collisions(self, arg: bool, /) -> None: ...

class SimpleIk:
    def __init__(self, arg0: roboplan_ext.core.Scene, arg1: SimpleIkOptions, /) -> None: ...

    def solveIk(self, arg0: roboplan_ext.core.CartesianConfiguration, arg1: roboplan_ext.core.JointConfiguration, arg2: roboplan_ext.core.JointConfiguration, /) -> bool: ...
